export const projectInfo = [
  {
    id: 1,
    name: "Agencyheight",
    tech: "Next.js Typescript Mantine UI Docker",
    imgPath: "/assets/project_img/agencyheight.png",
    description: "Inurance Agent Platform",
    url: "https://www.agencyheight.com/",
  },
  {
    id: 2,
    name: "Lama Adventure",
    tech: "HTML CSS Javascript Jquery Bootsrap",
    imgPath: "/assets/project_img/lama.png",
    description: "Travel Package Booking Website",
    url: "https://www.lamaadventure.com.np/",
  },
  {
    id: 3,
    name: "Educational Point of Light",
    tech: "HTML CSS Javascript Jquery Bootsrap",
    imgPath: "/assets/project_img/epl.png",
    description: "Educational and Playground Equipment Seller Website",
    url: "https://www.eplkid.com/",
  },
  {
    id: 1,
    name: "Agencyheight",
    tech: "Next.js Typescript Mantine UI Docker",
    imgPath: "/assets/agencyheight.png",
    description: "Inurance Agent Platform",
    url: "https://www.agencyheight.com/",
  },
  {
    id: 1,
    name: "Agencyheight",
    tech: "Next.js Typescript Mantine UI Docker",
    imgPath: "/assets/agencyheight.png",
    description: "Inurance Agent Platform",
    url: "https://www.agencyheight.com/",
  },
  {
    id: 1,
    name: "Agencyheight",
    tech: "Next.js Typescript Mantine UI Docker",
    imgPath: "/assets/agencyheight.png",
    description: "Inurance Agent Platform",
    url: "https://www.agencyheight.com/",
  },
];
